### ISSUE TITLE
Doesn't show distance numbers in Blender 4.3 and slower.

### ISSUE THREAD

**Issue by Foulvertex** [Jrome90/Fast-Loop#23]
Distance numbers aren't shown in the Blender 4.3. Also 4.2 extension branch have significantly slower overlay drawing.

**Comment by Jrome90** [comment]
I am not having any issues with Blender 4.3 with the 4.2 extension branch.
Is Distance Text toggled on under HUD Settings?
![image](https://github.com/user-attachments/assets/a18601b2-5a8d-4f69-8aad-526a64e24242)

**Comment by Jrome90** [comment]
I did come across an issue when undoing loop insertions that resulted in an exception. Which caused the Fast Loop operator to fail. I just pushed an update to address it.

But I'm not sure if your issue is related to that. I doubt it.

**Comment by Foulvertex** [comment]
Found the issue. Display units HUD was broken because scene distance units were set to "Adaptive". And slowdown is caused by some other add-on. Sorry for the inconvenience.

**Comment by Foulvertex** [comment]
UPD: Slowdowns still happen with ALL other add-ons disabled inside Blender even after restart. However, If I move/rename add-ons folder there are no slowdowns at all. I don't get why it's happening.

**Comment by Jrome90** [comment]
> UPD: Slowdowns still happen with ALL other add-ons disabled inside Blender even after restart. However, If I move/rename add-ons folder there are no slowdowns at all. I don't get why it's happening.

Are there any errors when it happens?
Would you be able to upload a short clip showing the slowdown?

**Comment by Foulvertex** [comment]
Sure!

This is clean Blender with only FastLoop enabled and no add-ons folder existing:

https://github.com/user-attachments/assets/87b7ed07-0ad1-469c-b35d-7eab94c343c2




This one is the same clean Blender with only FastLoop enabled but add-ons folder is present, but they are all disabled.


https://github.com/user-attachments/assets/612cd1c9-cb43-4773-9b0a-e00b845835e4


It may seem not much, but on heaver objects the lag is very noticeable, and honestly I have zero clue how disabled add-ons might affect anything.

Only errors in cosole is spam of this regardless of addons or not:

"Push constants have a minimum supported size of 128 bytes, however the constants added so far already reach 184 bytes. Consider using UBO."

**Comment by nurb2kea** [comment]
If you unzip an addon and put the folder into your ""blender addon folder"", your addon folder looks like this for example. 
![Screenshot 2024-11-24 at 11 09 56 pm](https://github.com/user-attachments/assets/f229640a-b5f8-4cc7-87bc-e72a9ef752ea)
When you startup Blender, the new folder and files will be build to help blender.
Means blender goes over everything in the ""blender addon folder"" to see new stuff (addons) & read the files it generated.
Means even with disabled addons, blender have seen all the pycache files... at startup.
And maybe this could slow down a bit. 
Also you are in a modal mode tools, that is always a bit tricky with dense mesh.

Hope that helps

![Screenshot 2024-11-24 at 11 09 23 pm](https://github.com/user-attachments/assets/0d8a921a-34dc-4ca1-a03e-665c318eedfd)

**Comment by Foulvertex** [comment]
But it happens even after a few mins of Blender being idle, also CPU usage is 0% before I use FastLoop, so I don't know. Also, the lag is noticeable on a simple cube too.

**Comment by Jrome90** [comment]
I wish I knew what the problem is.
Here is Fast Loop with 4.3.0 With addons:
![image](https://github.com/user-attachments/assets/1a294739-7c3b-455e-9bc0-bb36da8d32ad)

https://github.com/user-attachments/assets/bbcc74fb-6f0c-41db-833c-f57894f0d0db

The drawing speed seems reasonable. That is until I down into the denser geo.


Edit:
PC specs:
32 GB RAM
13900k
RTX 2070

**Comment by Foulvertex** [comment]
I suspected it might be connected to Edge Flow add-on, and I was right. After I commented the code in **get_edge_flow_version()** I got my performance back. Maybe it doesn't like too many add-on folders with many modules, etc? 

Regardless, thank you so much for this wonderful add-on, it works on very dense meshes and can't live without it.

**Comment by Jrome90** [comment]
> I suspected it might be connected to Edge Flow add-on, and I was right. After I commented the code in **get_edge_flow_version()** I got my performance back. Maybe it doesn't like too many add-on folders with many modules, etc?
> 
> Regardless, thank you so much for this wonderful add-on, it works on very dense meshes and can't live without it.

You found the issue? That's wonderful!
I will work on fixing that ASAP.
Thanks!

**Comment by Jrome90** [comment]
Just pushed an update that will cache the Set Flow version so that it doesn't loop through all addons every frame. I cannot believe that I never thought to do that. 
Sorry!

**Comment by Foulvertex** [comment]
Thank you very much for creating and supporting this gem!

P.S. Looking at the code, if the user doesn't have Edge Flow add-on installed, doesn't this function will try to find it every frame? I'm not a coder or anything though.

**Comment by Jrome90** [comment]
> Thank you very much for creating and supporting this gem!
> 
> P.S. Looking at the code, if the user doesn't have Edge Flow add-on installed, doesn't this function will try to find it every frame? I'm not a coder or anything though.

Yes, it will check every frame. But it is now cached and won't affect performance.

**Comment by nurb2kea** [comment]
> Just pushed an update that will cache the Set Flow version so that it doesn't loop through all addons every frame. I cannot believe that I never thought to do that.
> Sorry!

So where to find the updated version if not here!? :-)

**Comment by Jrome90** [comment]
> > Just pushed an update that will cache the Set Flow version so that it doesn't loop through all addons every frame. I cannot believe that I never thought to do that.
> > Sorry!
> 
> So where to find the updated version if not here!? :-)

You can find it here:
https://github.com/Jrome90/Fast-Loop/tree/Blender-4.2-Extension
